### PR TITLE
frontend project structure

### LINKED ISSUE #4: Add project structure for frontend app
Please add a structure for frontend project, don't forget to make your own branch and before you merge to develop branch please create pull request and add me and zaid as a reviewer

### PR DESCRIPTION
**Pull request by FarrelP**
Here's the frontend project structure. I propose this structure based on these two articles.

Reference:
1. https://itnext.io/how-to-structure-a-vue-js-project-29e4ddc1aeeb
2. https://vuex.vuejs.org/guide/structure.html

### CODE REVIEW

**Comment by afadhitya** [comment]
Hi @FarrelP 

I'll review your PR, but can you send me a screenshot of this project structure that remains on your local? Because you told me there are some folder was not pushed to the git because the folder is empty

**Comment by FarrelP** [comment]
Hi @afadhitya 

So here's the complete project structure.
image

**Comment by afadhitya** [comment]
Okay thanks.
I think it's enough for me. 
Let's wait for @MZaidA 's review until 20.00

**Comment by afadhitya** [comment]
Oh I forget, @FarrelP please add ".gitignore" file, you can use this reference https://github.com/vuejs/vuejs.org/blob/master/.gitignore 
and after you add, please push your commit to update this pull request

**Review by afadhitya — CHANGES_REQUESTED** [review]
please add ".gitignore" file, you can use this reference https://github.com/vuejs/vuejs.org/blob/master/.gitignore
and after you add, please push your commit to update this pull request

**Comment by FarrelP** [comment]
Hi @afadhitya 

Thank you for reminding me to add ".gitignore" file. I've already push the file on this branch 

`add_project_structure_frontend`

**Review by afadhitya — APPROVED** [review]

**Pull request merged**
